name: pawonkoe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  fluentui_system_icons: ^1.1.221
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  get: 4.6.6
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/

